# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025a72eca2cdb7bd53a3062e3394f265c0e764deaa9ad40895c602935ffaf2f4364544cb331c7850b04380b418e3ad75a7a83ec3ac3e55fc2ec19eff0161a00a

test:
  secret_key_base: 282dce574f097300345704f71117bf08b071212c04d53f4007d3656b1a5826c8a537aac99098f470a1d7c5bbb62d4b10bb28dd42ea78b69ecaf71d913a4c56b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
